FROM alpine:3.7

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

WORKDIR /app
COPY Gemfile* /

RUN apk --update add --no-cache \
    ruby-dev \
    build-base \
    ruby-bundler && bundle install

COPY . /app

CMD ["puma"]



