FROM alpine:3.7

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

WORKDIR /app
COPY Gemfile* /

RUN apk --update add --no-cache \
    ruby \
    ruby-dev \
    ruby-bundler \
    build-base \
    && bundle install \
    && apk del \
    ruby-bundler \
    build-base \
    ruby-dev \
    && rm -rf /var/cache/apk

COPY . /app

CMD ["puma"]