---
- name: Start gitlab-ci omnibus
  hosts: ubuntu-docker-app-0
  become: true
  tasks:
    - name: Start Docker daemon
      service:
        name: docker
        state: started

    - name: Create directories
      file:
        state: directory
        path: '/srv/gitlab/{{ item }}'
      loop:
        - config
        - data
        - logs

    - name: Config omnibus compose
      template:
        src: ../templates/docker-compose.j2
        dest: '/srv/gitlab/docker-compose.yml'

    - name: Start gitlab-ci
      docker_compose:
        project_src: '/srv/gitlab'
        state: present
